### ISSUE TITLE
Installation fails on macOS Sierra

### ISSUE THREAD

**Issue by mhulse** [jwagner/smartcrop-cli#10]
``` text
npm install smartcrop-cli --save-dev
/project/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /project/node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
Failed to execute 'node-gyp configure --fallback-to-build --module=/project/node_modules/opencv/build/opencv/v5.0.0/Release/node-v48-darwin-x64/opencv.node --module_name=opencv --module_path=/project/node_modules/opencv/build/opencv/v5.0.0/Release/node-v48-darwin-x64 --python=python2.7' (1)
/project
└── smartcrop-cli@1.0.2
```

I just installed OpenCV3 using:

``` bash
$ brew tap homebrew/science && brew install --HEAD opencv3
```

At a minimum, it might be cool to have a note in README about how to get opencv installed and that it is a hard dependency (as this CLI would not install without opencv … though, I obviously can't install with it either!).

Thanks for listening!

**Comment by tsboom** [comment]
I agree with mhulse. I had a lot of problems getting opencv to install as well. There's an [issue](https://github.com/peterbraden/node-opencv/issues/472)  at node-opencv where many others cannot install opencv either.

**Comment by jwagner** [comment]
At least in theory opencv is listed as a optional dependency: [package.json](https://github.com/jwagner/smartcrop-cli/blob/master/package.json).
I'll read up on optional dependencies and get back to this. Thanks for the bump as well, I somehow missed this issue.

**Comment by jwagner** [comment]
https://docs.npmjs.com/files/package.json#optionaldependencies

Node opencv is only loaded if requested via the command line and is wrapped in a try catch.
https://github.com/jwagner/smartcrop-cli/blob/master/smartcrop-cli.js#L59

Are you sure this is not just a warning?
Can you provide me a Dockerfile to reproduce the issue?

This does seem to work for me:
```
$ docker run -ti node:7.4.0 bash
$$ npm install -g smartcrop-cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: opencv@5.0.0 (node_modules/smartcrop-cli/node_modules/opencv):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm info ok 
$$ smartcrop 
Usage: smartcrop [OPTION] FILE [OUTPUT]
```

**Comment by mhulse** [comment]
Sorry I did not reply sooner. Thanks for the help @jwagner, I really appreciate it.

In my first post, I was just trying to install on my mac, no Docker (I have not used Docker, but I will try it out if that's the recommendation).

Also, my first post was for a local install. I normally don't install globally, if I can avoid it, but here's the output from that (if it is of any relevance):

```bash
$ npm install -g smartcrop-cli
/usr/local/bin/smartcrop -> /usr/local/lib/node_modules/smartcrop-cli/smartcrop-cli.js

> opencv@5.0.0 install /usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv
> node-pre-gyp install --fallback-to-build

/usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v5.0.0/Release/node-v51-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v5.0.0/Release/node-v51-darwin-x64" "--python=python2.7"
gyp ERR! cwd /usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/7.5.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v5.0.0/Release/node-v51-darwin-x64/opencv.node --module_name=opencv --module_path=/usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v5.0.0/Release/node-v51-darwin-x64 --python=python2.7' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:890:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv
node-pre-gyp ERR! node -v v7.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/7.5.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v5.0.0/Release/node-v51-darwin-x64/opencv.node --module_name=opencv --module_path=/usr/local/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v5.0.0/Release/node-v51-darwin-x64 --python=python2.7' (1)
/usr/local/lib
└─┬ smartcrop-cli@1.0.2
  ├─┬ concat-stream@1.6.0
  │ ├── inherits@2.0.3
  │ ├─┬ readable-stream@2.2.2
  │ │ ├── buffer-shims@1.0.0
  │ │ ├── core-util-is@1.0.2
  │ │ ├── isarray@1.0.0
  │ │ ├── process-nextick-args@1.0.7
  │ │ ├── string_decoder@0.10.31
  │ │ └── util-deprecate@1.0.2
  │ └── typedarray@0.0.6
  ├─┬ gm@1.23.0
  │ ├── array-parallel@0.1.3
  │ ├── array-series@0.1.5
  │ ├─┬ cross-spawn@4.0.2
  │ │ ├─┬ lru-cache@4.0.2
  │ │ │ ├── pseudomap@1.0.2
  │ │ │ └── yallist@2.0.0
  │ │ └─┬ which@1.2.12
  │ │   └── isexe@1.1.2
  │ └─┬ debug@2.2.0
  │   └── ms@0.7.1
  ├─┬ smartcrop-gm@1.0.2
  │ └── smartcrop@1.1.1
  ├── underscore@1.6.0
  └─┬ yargs@1.2.6
    └── minimist@0.1.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: opencv@5.0.0 (node_modules/smartcrop-cli/node_modules/opencv):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

I'll give Docker a try and let you know how that goes.

**Comment by mhulse** [comment]
Just realizing I have opencv3 installed, via Homebrew, and not opencv. I'm new to opencv, but I think that might be part of the problem.

**Comment by rmammina** [comment]
Running 
```
brew install homebrew/science/opencv
```
worked for me.

**Comment by mhulse** [comment]
> brew install homebrew/science/opencv

I need to try that again actually. I recently followed this:

http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/

But realized opencv3 is not exactly opencv

Looking like this is just boiling down to user inexperience. 😆 

Closing, and thanks for the help @rmammina and all.
