### ISSUE TITLE
Missing opencv

### ISSUE THREAD

**Issue by rmammina** [jwagner/smartcrop-cli#12]
On ubuntu 16.04, I have everything installed, but when running the command line with face detection, I get the following output.

```
{ Error: Cannot find module 'opencv'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/npm/lib/node_modules/smartcrop-cli/smartcrop-cli.js:61:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
skipping faceDetection
```

Note, when loading this via the command line in node, cv = require("opencv"); it seems load just fine. Not sure what I'm missing here.

**Comment by jwagner** [comment]
Can you please post the exact commands you used to install and run this that resulted in this message?
Even better would be a Dockerfile.

**Comment by jwagner** [comment]
No response, closing ticket.

**Comment by malvikiran** [comment]
@jwagner I am facing same issue.
It is not working in terminal:
smartcrop --width 100 --height 100 --faceDetection prints_13.jpg test.jpg

when I will remove faceDetection from command then it is working fine.

**Comment by dhowe** [comment]
same issue

**Comment by jwagner** [comment]
@dhowe did you check the installation instructions of node-opencv? https://github.com/peterbraden/node-opencv
