### ISSUE TITLE
Node 6 support

### ISSUE THREAD

**Issue by binarious** [jwagner/smartcrop-cli#6]
It doesn't seem to work with Node 6.
I got this error after updating:

```
> smartcrop --width 340 --height 340 input.jpg output.jpg
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/smartcrop-cli/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

**Comment by jwagner** [comment]
The error you get sounds like you didn't rebuild the package after updating node to 6.0. Try rebuilding or installing it again.

**Comment by binarious** [comment]
Right. Thank you!
